/**
 * Guides: short, honest how-to pages for the games (served at /guides/<slug>/).
 * Data only; apps/hub/guides/render.mjs turns it into static HTML at build time.
 * Rules (docs/seo.md): plain English, play chips only (never "$"), no mention of
 * AI or the school, nothing claimed that the game does not do.
 *
 * Section shapes: { h, p: [paragraphs], list: [items], table: { head, rows } }.
 */
export const GUIDES = [
  {
    slug: 'blackjack-basic-strategy',
    title: 'Blackjack basic strategy chart: hit, stand or double',
    description: 'A plain chart for six-deck blackjack where the dealer stands on 17: when to hit, stand or double, for hard and soft totals, and how to practise it free.',
    h1: 'Blackjack basic strategy: when to hit, stand or double',
    intro: 'Basic strategy is the best play for every hand you can be dealt, worked out by running millions of hands. It does not beat the house over a long run, but it cuts the house edge to about half a percent, which is as good as the rules allow. This chart is for six decks, with the dealer standing on every 17.',
    game: 'blackjack',
    sections: [
      { h: 'How to read the chart', p: ['Find your total down the side and the dealer’s face-up card across the top. H means hit, S means stand, D means double down if you can (otherwise hit), and Ds means double if you can (otherwise stand). Doubling is only possible on your first two cards.', 'Sundown Club’s Blackjack table currently lets you hit, stand or double. It has no splitting, insurance or surrender yet, so this page covers only those three moves. Where a pair would normally be split, play it as the total it makes.'] },
      { h: 'Hard totals (no ace, or an ace counted as 1)', table: { head: ['You have', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'A'], rows: [
        ['5 to 8', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H'],
        ['9', 'H', 'D', 'D', 'D', 'D', 'H', 'H', 'H', 'H', 'H'],
        ['10', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'H', 'H'],
        ['11', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'H'],
        ['12', 'H', 'H', 'S', 'S', 'S', 'H', 'H', 'H', 'H', 'H'],
        ['13 to 16', 'S', 'S', 'S', 'S', 'S', 'H', 'H', 'H', 'H', 'H'],
        ['17 or more', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S'],
      ] } },
      { h: 'Soft totals (an ace counted as 11)', table: { head: ['You have', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'A'], rows: [
        ['A,2 or A,3', 'H', 'H', 'H', 'D', 'D', 'H', 'H', 'H', 'H', 'H'],
        ['A,4 or A,5', 'H', 'H', 'D', 'D', 'D', 'H', 'H', 'H', 'H', 'H'],
        ['A,6', 'H', 'D', 'D', 'D', 'D', 'H', 'H', 'H', 'H', 'H'],
        ['A,7', 'S', 'Ds', 'Ds', 'Ds', 'Ds', 'S', 'S', 'H', 'H', 'H'],
        ['A,8 or A,9', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S'],
      ] } },
      { h: 'Why the chart looks like this', p: ['The dealer has to hit any total under 17, so a dealer showing a 4, 5 or 6 busts most often. That is why you stand on a stiff 12 to 16 against those cards and take the risk of busting against a 7 or higher, where the dealer is likely to make a hand.', 'You double when you are strong and the dealer is weak: 11 against anything but an ace, 10 against anything but a ten or ace, and 9 against 3 to 6. Soft hands cannot bust on one more card, so they are the cheapest hands to double.'] },
      { h: 'Habits that matter more than the chart', list: ['Keep your bet size the same. Raising it after a win or a loss does not change the odds.', 'Never take a hand because you have a feeling the next card is a ten. The shoe has six decks and no memory.', 'Play for fun with chips you do not mind losing. In Sundown Club the chips are play money and the club refills them when you run out.'] },
    ],
    related: ['how-to-play-blackjack', 'play-money-card-games-for-beginners'],
  },
  {
    slug: 'how-to-play-blackjack',
    title: 'How to play blackjack: rules for beginners',
    description: 'The rules of blackjack in plain English: card values, how a round goes, what hit, stand and double mean, what a blackjack pays, and what the dealer must do.',
    h1: 'How to play blackjack',
    intro: 'Blackjack is a card game against the dealer. You win by getting closer to 21 than the dealer without going over. It takes a minute to learn and a lifetime to stop second-guessing a 16.',
    game: 'blackjack',
    sections: [
      { h: 'Card values', list: ['Cards 2 to 10 are worth their number.', 'Jack, queen and king are worth 10.', 'An ace is worth 11, or 1 if 11 would take you over 21. A hand with an ace counted as 11 is called soft.'] },
      { h: 'How a round goes', list: ['You place a bet. At Sundown Club you click the chips or press the number keys.', 'You and the dealer get two cards. Yours are face up. The dealer has one up and one face down.', 'You act first. Hit (H) takes another card. Stand (S) keeps what you have. Double (D) doubles your bet, takes exactly one more card and ends your turn.', 'If you go over 21 you bust and lose at once.', 'The dealer turns the hidden card over. The dealer hits until reaching 17 or more and always stands on 17, including soft 17.', 'Closer to 21 wins. A tie is a push and your bet comes back.'] },
      { h: 'What wins pay', table: { head: ['Result', 'Pays'], rows: [['Win', 'Even money: 1 to 1'], ['Blackjack (an ace and a ten-value card on the first two cards)', '3 to 2'], ['Push', 'Your bet back'], ['Lose or bust', 'You lose the bet']] } },
      { h: 'Things to know', p: ['Sundown Club’s table uses six decks, shuffled by your browser’s secure random generator, and the dealer stands on every 17. The chips are play money: they cannot be bought, sold or turned into anything real.', 'A short tutorial in the game walks you through four practice hands with the cards chosen in advance, so each lesson shows exactly what it is teaching. The very first hand you play outside the tutorial is also a gentle practice deal, and the game says so; every hand after that is a fair shuffle.'] },
    ],
    related: ['blackjack-basic-strategy', 'play-money-card-games-for-beginners'],
  },
  {
    slug: 'texas-holdem-hand-rankings',
    title: 'Poker hand rankings from best to worst, with examples',
    description: 'The ten poker hands in order, from royal flush to high card, with an example of each and a note on how ties are broken in Texas Hold’em.',
    h1: 'Poker hand rankings, best to worst',
    intro: 'Every poker game uses the same ranking. In Texas Hold’em you make the best five-card hand from your two private cards and the five cards in the middle. Know this list and you can sit at any table.',
    game: 'holdem',
    sections: [
      { h: 'The hands', table: { head: ['Rank', 'Hand', 'Example'], rows: [
        ['1', 'Royal flush', 'A K Q J 10, all one suit'],
        ['2', 'Straight flush', '9 8 7 6 5, all one suit'],
        ['3', 'Four of a kind', 'K K K K 3'],
        ['4', 'Full house', 'Q Q Q 8 8'],
        ['5', 'Flush', 'Five cards of one suit, not in order'],
        ['6', 'Straight', '8 7 6 5 4, mixed suits (an ace can be high or low)'],
        ['7', 'Three of a kind', '7 7 7 K 2'],
        ['8', 'Two pair', 'J J 4 4 A'],
        ['9', 'One pair', '10 10 A 6 3'],
        ['10', 'High card', 'A J 8 5 2 with nothing else'],
      ] } },
      { h: 'Ties', p: ['Two players with the same type of hand are decided by the card ranks: a higher pair beats a lower pair, and if the pairs match the best extra card (the kicker) decides. Suits never break ties in Hold’em. If all five cards play, the pot is split.', 'The hand you show in Sundown Club at the end is named for you (for example “Two pair, Jacks and Fours”) so you can check the table’s call against this list.'] },
      { h: 'Common mix-ups', list: ['A flush beats a straight. It is rarer.', 'A full house beats a flush.', 'Three of a kind is not the same as a set. A set is a pocket pair plus one on the board, which only sounds fancier.'] },
    ],
    related: ['holdem-starting-hands', 'pot-odds-explained'],
  },
  {
    slug: 'holdem-starting-hands',
    title: 'Which Texas Hold’em starting hands to play',
    description: 'A simple guide to which two-card starting hands are worth playing in Texas Hold’em, and why playing fewer hands wins more at a six-seat table.',
    h1: 'Which Hold’em starting hands to play',
    intro: 'The easiest way to improve at Texas Hold’em is to play fewer hands. Most beginners play far too many, and lose chips with hands that are second best when it matters. This is a plain-English guide for a six-seat game.',
    game: 'holdem',
    sections: [
      { h: 'A simple rule of thumb', p: ['At a six-seat table, with fewer players to beat, you can play more hands than at a full ring. Even so, about a quarter to a third of your hands is plenty.'] },
      { h: 'Hands worth raising with', list: ['Any pair of eights or better (8 8 up to A A).', 'Ace with king, queen or jack.', 'King with queen, suited or not.', 'Suited connectors from 10 9 up to the high ones (J 10, Q J). They make straights and flushes and win big pots.'] },
      { h: 'Hands worth playing if nobody has raised', list: ['Small pairs (2 2 to 7 7). Call cheap and hope to hit a third card on the flop.', 'Ace with any suited card (A 5 suited, for example), because of flush chances.', 'Suited connectors lower down (7 6, 6 5).', 'King with jack, or queen with jack.'] },
      { h: 'Hands to throw away', list: ['Unsuited cards with a gap, like 9 4 or J 3.', 'Weak aces without a suit, like A 6 offsuit. They often make a pair that is beaten by a better ace.', 'Any hand when someone has raised hard and you have only a small card to show.'] },
      { h: 'Position matters', p: ['Acting last is a big advantage, because you see what everyone does first. The closer you sit after the dealer button, the more hands you can play. Early on, in the first seats to act, play only the strong hands.', 'At the club’s table the five regulars play differently: one is tight, one sharp, one wild, one calls too much and one is steady. Watching who raises and who only calls teaches you more than any chart.'] },
    ],
    related: ['texas-holdem-hand-rankings', 'pot-odds-explained'],
  },
  {
    slug: 'pot-odds-explained',
    title: 'Pot odds explained: when is calling worth it?',
    description: 'Pot odds in plain English with worked examples: how to tell whether a call in poker pays off, and how to count outs for a flush or straight draw.',
    h1: 'Pot odds explained',
    intro: 'Pot odds tell you whether a call is worth the price. It is simple arithmetic, and it is what separates a guess from a decision.',
    game: 'holdem',
    sections: [
      { h: 'The idea', p: ['Compare what it costs to call with what you could win. If you call 20 to win a pot of 80, you are paying 20 to win 100 in total (80 plus your own call), so you need to win one time in five (20 divided by 100) to break even.'] },
      { h: 'The formula', list: ['Pot odds = the amount you must call, divided by (the pot plus your call).', 'If your chance of winning is higher than that number, calling pays off over time.'] },
      { h: 'Counting outs', p: ['An out is a card that completes your hand. With a flush draw after the flop you have nine outs. With an open-ended straight draw you have eight.', 'A quick estimate: multiply your outs by 4 for your chance of hitting by the river from the flop, or by 2 if there is only one card to come. Nine outs is about 36 percent from the flop (the exact figure is a little less, near 35).'] },
      { h: 'A worked example', p: ['The pot is 60. An opponent bets 20, so the pot is 80 and it costs you 20 to call. You need 20 divided by 100, or 20 percent. You hold a flush draw with two cards to come: about 35 percent. Calling is correct.', 'Now the opponent bets 80 into a pot of 60. It costs 80 to win 220 in total. You need 80 divided by 220, about 36 percent. The same draw is a close call, not a clear one.'] },
      { h: 'Keep in mind', list: ['Pot odds are about the price now. Good players also think about what they might win on later cards.', 'Bots at the Sundown Club table use pot odds too, with some randomness. Their bets give you real prices to practise on, for play chips only.'] },
    ],
    related: ['holdem-starting-hands', 'texas-holdem-hand-rankings'],
  },
  {
    slug: 'video-poker-strategy-jacks-or-better',
    title: 'Jacks or Better video poker strategy: what to hold',
    description: 'What to hold in 9/6 Jacks or Better video poker, in order of priority, with the full-pay paytable and an honest note on what perfect play returns.',
    h1: 'Jacks or Better video poker strategy',
    intro: 'Video poker gives you five cards and one chance to swap any of them. The skill is deciding which to keep. On a 9/6 full-pay Jacks or Better machine, perfect play returns about 99.5 percent over the long run, which is why it is the one casino-style game where strategy matters most.',
    game: 'videopoker',
    sections: [
      { h: 'The paytable (per coin, at five coins)', table: { head: ['Hand', 'Pays at 5 coins'], rows: [['Royal flush', '4,000'], ['Straight flush', '250'], ['Four of a kind', '125'], ['Full house', '45'], ['Flush', '30'], ['Straight', '20'], ['Three of a kind', '15'], ['Two pair', '10'], ['Jacks or better', '5']] } },
      { h: 'What to hold, best first', list: ['A made royal flush, straight flush or four of a kind.', 'Four cards to a royal flush.', 'A made full house, flush, three of a kind or straight.', 'Four cards to a straight flush.', 'Two pair.', 'A high pair (jacks, queens, kings or aces).', 'Three cards to a royal flush.', 'Four cards to a flush.', 'A low pair (tens down to twos).', 'Four cards to an open-ended straight.', 'Two suited high cards (any two of A, K, Q, J of one suit).', 'Three cards to a straight flush.', 'Two unsuited high cards, such as K and Q.', 'Suited ten with a jack, queen or king.', 'One high card. If you have nothing worth keeping, throw all five away.'] },
      { h: 'Notes on the list', p: ['This is the standard order of priority for full-pay Jacks or Better. A few close calls depend on the exact cards, but following the list will be right nearly every time.', 'Always play five coins. The royal flush jumps from 250 coins per coin bet to 800 at the maximum, and the other hands pay in step. Playing fewer coins is the one real mistake the machine lets you make.'] },
      { h: 'Be realistic', list: ['A royal flush comes about once in 40,000 hands.', 'Strategy lowers the cost of playing. It does not turn the machine into a winner.', 'Sundown Club’s machine uses play chips. There is a practice tutorial that plays one guided hand with you.'] },
    ],
    related: ['play-money-card-games-for-beginners', 'texas-holdem-hand-rankings'],
  },
  {
    slug: 'how-to-park-a-car',
    title: 'How to park a car: reverse, parallel and bay parking tips',
    description: 'A step-by-step guide to parking properly: how to use mirrors, when to reverse in, how to steer in a bay, and how to practise safely in a free driving game.',
    h1: 'How to park a car properly',
    intro: 'Good parking is mostly about speed and sight. Go slowly, look everywhere, and let the car do the turning. These tips apply to bays in car parks, and you can practise them in Parking Precision for free, with nothing to dent.',
    game: 'parking',
    sections: [
      { h: 'Before you turn the wheel', list: ['Slow to walking pace. Parking is done at a crawl.', 'Pick the bay early and look past it for traffic and people.', 'Check your mirrors and, if you have one, the reversing camera and sensors.'] },
      { h: 'Bay parking (reverse in)', list: ['Drive past the bay until your car’s rear is a little beyond it, with a car-width of space to the side.', 'Stop. Engage reverse and turn the wheel fully towards the bay.', 'Reverse slowly until the car points into the bay, then straighten the wheel and keep going.', 'When your mirrors show equal space on both sides, stop. Do not use the car in front as a reference.'] },
      { h: 'Why reverse in?', p: ['Reversing into a bay is easier because the front wheels steer. You get the sharp turn at the start, and you drive out forwards with a clear view of the road.'] },
      { h: 'Common mistakes', list: ['Going too fast. Every parking mistake gets worse with speed.', 'Turning too late, then having to correct.', 'Stopping when the car is straight instead of when it is in the middle of the bay.', 'Not looking. Check over your shoulder at least once.'] },
      { h: 'Practise it', p: ['In Parking Precision you drive in first person, park in a glowing bay, and get a score out of 100. There are 17 car parks, from an easy first level to a rooftop and an underground garage. The game shows what went wrong afterwards, so you can fix it on the next try.'] },
    ],
    related: ['parking-precision-scoring', 'drifting-basics-for-beginners'],
  },
  {
    slug: 'parking-precision-scoring',
    title: 'Parking Precision scoring: how the score out of 100 works',
    description: 'How Parking Precision scores a park out of 100: placement, depth, alignment, time and finesse, what earns three stars, and how to get closer to a perfect score.',
    h1: 'How Parking Precision scores your park',
    intro: 'Every park is scored out of 100. The score is made of five parts, and knowing the weights tells you where the points are. This is how the game adds them up.',
    game: 'parking',
    sections: [
      { h: 'The five parts', table: { head: ['Part', 'Points', 'What it judges'], rows: [['Placement', '30', 'How centred you are, side to side. This matters most, because sitting off-centre puts your door against the neighbour.'], ['Alignment', '25', 'How straight the car is in the bay.'], ['Depth', '20', 'How far forwards or back you stopped.'], ['Time', '15', 'Your time against the level’s par time.'], ['Finesse', '10', 'Nothing hit. Each bump or cone costs points.']] } },
      { h: 'Stars', p: ['A score of 88 or more earns three stars, 68 or more earns two, and anything below that on a completed park earns one.'] },
      { h: 'Where players lose points', list: ['Sliding in off-centre. Side-to-side accuracy is worth more than depth, so fix that first.', 'Rushing. Time is only 15 points, so a slow, clean park beats a fast, scruffy one.', 'Clipping a pillar or cone. Bumps cost more than a few seconds do.', 'Stopping crooked. Straighten the wheel as you finish.'] },
      { h: 'Getting better', p: ['Retry a level as often as you like. Your best run on each level is kept, and the game can show it as a ghost car next to you on the next attempt. After a park, the results screen says where the points went.'] },
    ],
    related: ['how-to-park-a-car', 'drifting-basics-for-beginners'],
  },
  {
    slug: 'drifting-basics-for-beginners',
    title: 'Drifting basics: how to hold a slide and build a drift score',
    description: 'The basics of drifting in a driving game: slip angle, counter-steering and throttle control, and how Night Drive’s test drive scores a drift.',
    h1: 'Drifting basics for beginners',
    intro: 'A drift is a controlled slide: the rear of the car steps out, and you keep it there with the wheel and the throttle. Learn it in a game first. Night Drive’s test drive has a drift pad for exactly this.',
    game: 'racing',
    sections: [
      { h: 'The three ingredients', list: ['Weight transfer. Turn in and lift off, or brake briefly, so the weight moves to the front and the rear gets light.', 'Throttle. Power makes the rear tyres slide. Too little and the car grips; too much and it spins.', 'Counter-steer. Once the rear steps out, steer the front wheels the opposite way, towards where you want to go.'] },
      { h: 'Slip angle', p: ['Slip angle is the angle between where the car points and where it is travelling. In Night Drive’s test drive a drift only scores once the angle is between about 15 and 50 degrees: the score builds with speed and with how far sideways you are, and gets full value at the larger angles.'] },
      { h: 'How the score builds', list: ['The score is your speed multiplied by an angle factor, and then by a combo.', 'Keep a drift going and the combo grows, by a tenth for every two seconds of continuous sliding, up to three times.', 'Straighten up and the combo drains. When it empties, the drift score resets.'] },
      { h: 'A way to practise', list: ['Start on the drift pad at a gentle speed.', 'Turn in, give a burst of throttle, and catch the slide with the wheel.', 'Hold a steady throttle. Small, smooth wheel movements keep the slide steady; big ones throw you into a spin.', 'Try the preset tunes. Setup changes how forgiving the car feels, and the game lets you try every slider.'] },
      { h: 'Remember', p: ['Drifting on a road is dangerous and illegal. This is a game for practising the ideas in a place where nothing can go wrong. Night Drive is a test drive for now, with the story still being built.'] },
    ],
    related: ['how-to-park-a-car', 'parking-precision-scoring'],
  },
  {
    slug: 'play-money-card-games-for-beginners',
    title: 'Play-money card games for beginners: how to practise for free',
    description: 'What play-money card games are, why they are a good way to learn blackjack, poker and video poker, and how to keep it fun: no real money, no sign-up.',
    h1: 'Play-money card games for beginners',
    intro: 'A play-money game uses pretend chips. You get all the thinking of blackjack, poker or video poker, with none of the risk. That makes it the best place to learn, and a good way to just enjoy cards.',
    game: 'blackjack',
    sections: [
      { h: 'What “play money” means here', p: ['At Sundown Club the chips in Blackjack, Hold’em and Video Poker are not real money. They cannot be bought, sold or cashed out, and nothing you win has any value outside the game. No payment details are ever asked for. When your chips run low the club tops them up, so a bad run never ends your evening.'] },
      { h: 'Why practising this way works', list: ['You can try a risky play to see what happens, which you would never do with something at stake.', 'You see thousands of hands quickly, so patterns become clear.', 'Mistakes are free, so you learn from them rather than hide them.'] },
      { h: 'A sensible way to start', list: ['Learn the rules in the game’s short tutorial.', 'Start with Blackjack. It is the simplest, and has a chart you can learn.', 'Move to Video Poker once you know the poker hands. It teaches you to think about probabilities.', 'Try Hold’em last. It adds other players and the skill of reading them.'] },
      { h: 'Keeping it fun', list: ['Play for the thinking, not to chase a number.', 'Take a break after an hour or so. The club suggests one.', 'If cards ever stop being fun, stop. Real gambling is not a game, and these skills will not make it safe.'] },
    ],
    related: ['how-to-play-blackjack', 'blackjack-basic-strategy', 'video-poker-strategy-jacks-or-better'],
  },
];
export const GUIDE_BY_SLUG = Object.fromEntries(GUIDES.map((g) => [g.slug, g]));
