/**
 * build-tokens.mjs — writes packages/shared/design/tokens.css from tokens.js,
 * the one source of truth (docs/design/SYSTEM.md). Run after any token change:
 *
 *   node tools/build-tokens.mjs
 *
 * tools/design-check.mjs fails if tokens.css is out of date.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import * as T from '../packages/shared/design/tokens.js';

export const CSS_PATH = 'packages/shared/design/tokens.css';

const rgb = (hex) => [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16));
const glassOf = (hex) => `rgb(${rgb(hex).join(' ')} / ${T.glass.alpha})`;
const kebab = (s) => s.replace(/[A-Z]/g, (c) => '-' + c.toLowerCase());

function skyVars(p) {
  return [
    `--s0: ${p.s0};`, `--s1: ${p.s1};`, `--s2: ${p.s2};`, `--s3: ${p.s3};`,
    `--glass: ${glassOf(p.s1)};`,
    `--sun: ${p.sun};`, `--on-sun: ${p.onSun};`,
  ];
}

function paperVars(p) {
  return [`--s0: ${p.s0};`, `--s1: ${p.s1};`, `--s2: ${p.s2};`, `--s3: ${p.s3};`, `--glass: rgb(${rgb(p.s1).join(' ')} / ${T.paper.glassAlpha});`];
}

function typeVars() {
  const out = [];
  for (const [role, t] of Object.entries(T.type)) {
    out.push(`--text-${role}: ${t.weight} ${t.size}/${t.leading} var(--font-${t.font});`);
    out.push(`--tracking-${role}: ${t.tracking};`);
  }
  return out;
}

export function renderCss() {
  const L = [];
  const block = (sel, lines) => { L.push(`${sel} {`, ...lines.map((l) => `  ${l}`), '}', ''); };
  L.push('/* Generated by tools/build-tokens.mjs from packages/shared/design/tokens.js. Do not edit by hand. */', '');

  block(':root', [
    'color-scheme: dark;',
    '/* type */',
    `--font-display: ${T.fonts.display};`, `--font-ui: ${T.fonts.ui};`, `--font-mono: ${T.fonts.mono};`,
    ...typeVars(),
    '/* ink (same on every surface and in every sky) */',
    `--ink-1: ${T.ink.primary};`, `--ink-2: ${T.ink.secondary};`, `--ink-3: ${T.ink.tertiary};`,
    '/* surfaces: golden hour by default; data-sky switches the phase */',
    ...skyVars(T.sky.golden),
    `--glass-blur: ${T.glass.blur};`, `--glass-saturate: ${T.glass.saturate};`,
    '/* accent: the sun until a game sets data-game */',
    '--accent: var(--sun);', '--on-accent: var(--on-sun);',
    '--accent-text: var(--accent); /* the game colour as text: deeper on paper */',
    '--accent-paper-ink: #2c2a30;',
    '--accent-soft: color-mix(in oklab, var(--accent) 16%, transparent);',
    '/* results */',
    `--win: ${T.result.win};`, `--lose: ${T.result.lose};`, `--push: ${T.result.push};`,
    '/* space and layout */',
    ...Object.entries(T.space).map(([k, v]) => `--space-${k}: ${v};`),
    ...Object.entries(T.layout).map(([k, v]) => `--${kebab(k)}: ${v};`),
    '/* shape */',
    ...Object.entries(T.radius).map(([k, v]) => `--r-${k}: ${v};`),
    '/* depth: shadows and light, never hard borders */',
    `--edge: ${T.shadow.edge};`, `--lift-1: ${T.shadow.lift1};`, `--lift-2: ${T.shadow.lift2};`, `--lift-3: ${T.shadow.lift3};`,
    `--selected: ${T.shadow.selected};`, `--focus-ring: ${T.shadow.focus};`, `--scrim: ${T.shadow.scrim};`,
    '/* motion */',
    ...Object.entries(T.motion.ease).map(([k, v]) => `--ease-${kebab(k)}: ${v};`),
    ...Object.entries(T.motion.ms).map(([k, v]) => `--dur-${k}: ${v}ms;`),
    `--press-scale: ${T.motion.pressScale};`, `--enter-scale: ${T.motion.enterScale};`,
    `--enter-rise: ${T.motion.enterRise};`, `--stagger: ${T.motion.stagger}ms;`,
    '--move: 1; /* multiply every travel distance by this: 0 under reduced motion */',
    '/* stacking */',
    ...Object.entries(T.z).map(([k, v]) => `--z-${k}: ${v};`),
  ]);

  for (const phase of ['dusk', 'night']) block(`[data-sky="${phase}"]`, skyVars(T.sky[phase]));

  // Paper (the card tables): same token names, light surface, dark ink.
  block('[data-surface="paper"]', [
    'color-scheme: light;',
    ...paperVars(T.paper.sky.golden),
    `--ink-1: ${T.paper.ink.primary};`, `--ink-2: ${T.paper.ink.secondary};`, `--ink-3: ${T.paper.ink.tertiary};`,
    `--win: ${T.paper.result.win};`, `--lose: ${T.paper.result.lose};`, `--push: ${T.paper.result.push};`,
    `--edge: ${T.paper.edge};`,
    '--accent-text: var(--accent-paper-ink);',
  ]);
  for (const phase of ['dusk', 'night']) block(`[data-surface="paper"][data-sky="${phase}"], [data-sky="${phase}"] [data-surface="paper"]`, paperVars(T.paper.sky[phase]));

  for (const [id, g] of Object.entries(T.games)) block(`[data-game="${id}"]`, [`--accent: ${g.accent};`, `--on-accent: ${g.onAccent};`, `--accent-paper-ink: ${g.paperInk};`]);

  L.push('@media (prefers-reduced-motion: reduce) {');
  L.push('  :root { --move: 0; --press-scale: 1; --enter-scale: 1; --stagger: 0ms; --dur-scene: 200ms; --dur-moment: 200ms; }', '}', '');
  L.push('@media (prefers-reduced-transparency: reduce) {');
  L.push('  :root, [data-sky], [data-surface] { --glass: var(--s1); --glass-blur: 0px; --glass-saturate: 1; }', '}', '');
  L.push('@media (prefers-contrast: more) {');
  L.push('  :root { --ink-2: var(--ink-1); --ink-3: var(--ink-1); --edge: inset 0 0 0 1px rgb(243 231 216 / 0.55); }',
    '  [data-surface="paper"] { --ink-2: var(--ink-1); --ink-3: var(--ink-1); --edge: inset 0 0 0 1px rgb(44 42 48 / 0.6); }', '}');
  return L.join('\n') + '\n';
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(CSS_PATH, renderCss());
  console.log(`wrote ${CSS_PATH}`);
}
